# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '00 1 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale as it has not received any activity recently. It will be closed soon if no more activity occurs.'
        stale-pr-message: 'This PR has been marked as stale as it has not received any activity recently. It will be closed soon if no more activity occurs.'
        days-before-issue-stale: 30
        days-before-pr-stale: 30
        days-before-close: 15
        exempt-issue-labels: 'P-high,T-feature,T-debt,T-meta,T-perf,T-question,good first issue'
        stale-issue-label: 'S-stale'
        stale-pr-label: 'S-stale'
        exempt-all-milestones: true
        exempt-all-assignees: true
